import React, { useEffect, useState } from 'react';
import { Download, ShieldCheck, X } from 'lucide-react';
import { useGameStore } from '../../stores/useGameStore';
import { usePersonalizationStore } from '../../stores/usePersonalizationStore';
import { parentGate } from '../../services/personalization/parentGate';
import { renderCaptainId } from '../../services/personalization/captainIdRenderer';
import { shareCaptainId } from '../../services/personalization/captainIdExport';
import { parentFeatureFlags } from '../../config/parentFeatureFlags';

export const CaptainIdStudio: React.FC<{ childId: string; onClose: () => void }> = ({ childId, onClose }) => {
  const user = useGameStore((state) => state.user);
  const completedNodes = useGameStore((state) => state.completedNodes);
  const nodeStars = useGameStore((state) => state.nodeStars);
  const child = usePersonalizationStore((state) => state.children[childId]);
  const assets = usePersonalizationStore((state) => state.assets);
  const [previewUrl,setPreviewUrl]=useState<string|null>(null); const [blob,setBlob]=useState<Blob|null>(null); const [filename,setFilename]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('');
  const avatarAsset=assets.find((asset)=>asset.id===child?.avatarAssetId);const approvedFlagAsset=child?.flagReviewStatus==='APPROVED_LOCAL'?assets.find((asset)=>asset.id===child.flagAssetId):null;
  const createPreview=async()=>{setBusy(true);setError('');try{const result=await renderCaptainId({nickname:user.name,grade:user.grade,title:'Nhà thám hiểm Nova',totalStars:Object.values(nodeStars).reduce((sum,value)=>sum+value,0),completedCoordinates:Object.keys(completedNodes).length,avatarAsset,approvedFlagAsset,presetAvatar:user.avatar});if(previewUrl)URL.revokeObjectURL(previewUrl);setBlob(result.blob);setFilename(result.filename);setPreviewUrl(URL.createObjectURL(result.blob));}catch(value){setError(value instanceof Error?value.message:'Không thể tạo Space ID.');}finally{setBusy(false);}};
  useEffect(()=>{void createPreview();},[]);
  useEffect(()=>()=>{if(previewUrl)URL.revokeObjectURL(previewUrl);},[previewUrl]);
  const exportCard=async()=>{if(!blob)return;const pin=prompt(parentFeatureFlags.demoAccess?'Nhập mật khẩu demo để xuất Space ID:':'Nhập PIN phụ huynh 6 số để xuất Space ID:')??'';const valid=parentFeatureFlags.demoAccess?/^\d{4}$/.test(pin):/^\d{6}$/.test(pin);if(!valid){setError(parentFeatureFlags.demoAccess?'Mật khẩu demo phải gồm đúng 4 số.':'PIN phải gồm đúng 6 số.');return;}setBusy(true);setError('');setMessage('');try{await parentGate.authorizeWithPin(pin,'CARD_EXPORT',true);const result=await shareCaptainId({blob,mimeType:'image/png',width:1080,height:1920},filename);setMessage(result==='downloaded'?'Đã tải Space ID xuống thiết bị.':'Đã mở bảng chia sẻ của thiết bị.');}catch(value){if(!String(value).toLowerCase().includes('cancel'))setError(value instanceof Error?value.message:'Không thể xuất Space ID.');}finally{setBusy(false);}};
  return <div className="fixed inset-0 z-[90] flex items-end justify-center bg-slate-950/90 sm:items-center" role="dialog" aria-modal="true" aria-label="Space ID"><div className="flex max-h-[96dvh] w-full max-w-lg flex-col overflow-hidden rounded-t-[32px] border border-cyan-400/40 bg-[#080d1d] sm:rounded-[32px]"><header className="flex items-center justify-between border-b border-slate-800 px-4 py-3"><div><h2 className="font-black text-cyan-200">Space ID</h2><p className="text-[11px] text-slate-400">Xem trước local · 1080 × 1920</p></div><button onClick={onClose} className="rounded-xl bg-slate-800 p-2" aria-label="Đóng Space ID"><X className="h-4 w-4"/></button></header><div className="flex-1 space-y-3 overflow-y-auto p-4">{previewUrl?<img src={previewUrl} alt="Xem trước Space ID" className="mx-auto max-h-[62dvh] rounded-2xl border border-cyan-400/40 object-contain"/>:<div className="flex aspect-[9/16] items-center justify-center rounded-2xl bg-slate-900 text-sm text-slate-400">Đang tạo bản xem trước…</div>}<div className="rounded-xl bg-slate-900 p-3 text-xs text-slate-300"><ShieldCheck className="mr-1 inline h-4 w-4 text-cyan-300"/>Mỗi lần xuất đều cần nhập lại PIN phụ huynh. Thẻ không chứa ID nội bộ, email, trường học hoặc đường dẫn file.</div><button data-testid="export-space-id" disabled={busy||!blob} onClick={()=>void exportCard()} className="w-full rounded-xl bg-gradient-to-r from-cyan-400 to-blue-500 px-4 py-3 text-sm font-black text-slate-950 disabled:opacity-40"><Download className="mr-1 inline h-4 w-4"/>Xuất / lưu Space ID</button>{message&&<p className="rounded-xl bg-emerald-950 p-2 text-xs text-emerald-300">{message}</p>}{error&&<p role="alert" className="rounded-xl bg-rose-950 p-2 text-xs text-rose-300">{error}</p>}</div></div></div>;
};
